import React, { useEffect, useState } from 'react'
import Head from 'next/head'

const CovidInfo = () => {
    const [covid, setCovid] = useState([]);

    const getCovidInfo = async () => {
        const res = await fetch("https://data.covid19india.org/data.json");
        const actualResult = await res.json();
        setCovid(actualResult.statewise);
    }
    useEffect(() => {
        getCovidInfo();
    }, [])

    return (
        <>
            <Head>
                <title>Covid-19-Info</title>
                <meta name="description" content="Generated by Muhammad Nasir" />
                <link rel="icon" href="/images/LN1.png" />
            </Head>
            <section className="text-gray-600 body-font">
                <div className="container px-5 py-24 mx-auto">
                    <div className="flex flex-col text-center w-full mb-20">
                        <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Live Information</h1>
                        <p className="lg:w-2/3 mx-auto leading-relaxed text-base">COVID-19 CRONA-VIRUS TRACKER.</p>
                    </div>
                    <div className="flex flex-wrap -m-4 text-center">
                        {covid.map((curValue, index) => {
                            return (
                                <div key={index} className="p-4 md:w-1/4 sm:w-1/2 mx-auto">
                                    <div className="border-2 border-gray-200 px-10 py-6 rounded-lg">
                                        <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                                            <path d="M8 17l4 4 4-4m-4-5v9"></path>
                                            <path d="M20.88 18.09A5 5 0 0018 9h-1.26A8 8 0 103 16.29"></path>
                                        </svg>
                                        <h6 className="title-font font-medium text-sm text-gray-900">Active Case : {curValue.active}</h6>
                                        <h6 className="title-font font-medium text-sm text-gray-900">confirmed Case : {curValue.confirmed}</h6>
                                        <h6 className="title-font font-medium text-red-700 text-sm">Deaths : {curValue.deaths}</h6>
                                        <h6 className="title-font font-medium text-sm text-gray-900">Recovered : {curValue.deltarecovered}</h6>
                                        <h6 className="title-font font-medium text-sm text-gray-900">Updated Time : {curValue.lastupdatedtime}</h6>
                                        <h6 className="title-font font-medium text-sm text-gray-900">State : {curValue.state}</h6>
                                        <h6 className="title-font font-medium text-sm text-gray-900">State Code : {curValue.statecode}</h6>
                                    </div>
                                </div>
                            )
                        })
                        }
                    </div>
                </div>
            </section>
        </>
    )
}

export default CovidInfo