import React, { useState } from 'react'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head'

const Greeting = () => {
    const [greeting, setGreeting] = useState("");
    const [color, setColor] = useState("black");
    const inputEvent = (event) => {
        const date = event.target.value;
        if (date >= '00:00' && date <= '12:00') {
            setGreeting("Good Morning")
            setColor('green');
            toast.success('🦄 Good Morning!', {
                position: "top-center",
                autoClose: 1000,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                draggable: true,
                progress: undefined,
            });
        }
        else if (date > "12:00" && date <= "19:00") {
            setGreeting("Good Evening")
            setColor('orange');
            toast.warning('🦄 Good Evening!', {
                position: "top-center",
                autoClose: 1000,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                draggable: true,
                progress: undefined,
            });

        }
        else {
            setGreeting("Good Night")
            setColor('red');
            toast('🦄 Good Night!', {
                position: "top-center",
                autoClose: 1000,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                draggable: true,
                progress: undefined,
            });

        }
    }
    return (
        <>
            <Head>
                <title>Greeting</title>
                <meta name="description" content="Generated by Muhammad Nasir" />
                <link rel="icon" href="/images/LN1.png" />
            </Head>
            <div className="flex lg:w-1/2 sm:w-full sm:flex-row flex-col mx-auto px-8 sm:space-x-4 sm:space-y-0 space-y-4 sm:px-0 items-end">
                <div className="relative flex-grow w-full">
                    <label htmlFor="full-time" className="leading-7 text-sm text-gray-600">Time</label>
                    <input value={greeting} onChange={inputEvent} type="time" id="full-time" name="full-time" placeholder='Pick Time' autoComplete='of' className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-transparent focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" />
                </div>
            </div>
            <div className="flex lg:w-1/2 sm:w-full sm:flex-row flex-col mx-auto px-8 sm:space-x-4 sm:space-y-0 space-y-4 sm:px-0 items-start">
                <h1>Hello Sir, <span style={{ color }}> {greeting}</span></h1>
            </div>
            <div>
                <ToastContainer
                    position="top-center"
                    autoClose={1000}
                    hideProgressBar={false}
                    newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                />
            </div>
        </>
    )
}

export default Greeting