import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import Main from './Main';

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Print-Table</title>
          <meta name="description" content="Generated by Muhammad Nasir" />
          <link rel="icon" href="/images/LN1.png" />
        </Head>
        <Main />
      </div>
    </>
  )
}
